[authentication]
username = 'example@your.email.com'
password = 'your_password'

[proxy]
ip_port = "127.0.0.1:57777"

[config]
save_folder = 'E:\Dataset\Copernicus\S2L2A\2025\0103'  # use single quotes to avoid escape backslash
num_workers = 3
random_pause_prob = 0.0

[filter]
roi_json_path = 'D:\Downloads\Compressed\DL_FIRE_SV-C2_674351\fire_archive_SV-C2_674351_2025-01-05_concave_hull.geojson'

[search_url]
default = "https://catalogue.dataspace.copernicus.eu/odata/v1/Products?&$filter=((Collection/Name%20eq%20%27SENTINEL-2%27%20and%20(Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27instrumentShortName%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27MSI%27)%20and%20Attributes/OData.CSC.DoubleAttribute/any(att:att/Name%20eq%20%27cloudCover%27%20and%20att/OData.CSC.DoubleAttribute/Value%20le%2030)%20and%20(contains(Name,%27L2A%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;POLYGON%20((-59.414%20-82.631,%2094.57%20-82.631,%2094.57%2083.792,%20-59.414%2083.792,%20-59.414%20-82.631))%27)))%20and%20Online%20eq%20true)%20and%20ContentDate/Start%20ge%202025-01-05T00:00:00.000Z%20and%20ContentDate/Start%20lt%202025-01-05T23:59:59.999Z)&$orderby=ContentDate/Start%20desc&$expand=Attributes&$count=True&$top=50&$expand=Assets&$skip=0"
