[workspace]
authors = ["Awenforever <king_wedo@163.com>"]
channels = ["conda-forge"]
name = "SentinelDownloader"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
dl = 'python .\copernicus_downloader_v2.2.py'

[dependencies]
python = ">=3.12.12,<3.13"
matplotlib = ">=3.10.7,<4"
pixi-pycharm = ">=0.0.9,<0.0.10"
gdal = ">=3.10.3,<4"
rasterio = ">=1.4.3,<2"
sentinelhub = ">=3.11.3,<4"
folium = ">=0.20.0,<0.21"
openai = ">=2.6.1,<3"
opencv = ">=4.12.0,<5"
rich = ">=14.2.0,<15"
geopandas = ">=1.1.1,<2"
requests = ">=2.32.5,<3"
keyboard = ">=0.13.5,<0.14"
shapely = ">=2.1.2,<3"
python-dotenv = ">=1.2.1,<2"
tomlkit = ">=0.13.3,<0.14"

[pypi-dependencies]
esa-snappy = ">=1.1.0, <2"

