[workspace]
authors = ["ahuiforever <king_wedo@163.com>"]
channels = ["conda-forge"]
name = "SentinelDownloader"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.7,<4"
python = "3.10.*"
pixi-pycharm = ">=0.0.9,<0.0.10"
gdal = "3.8.*"
rasterio = ">=1.3.10,<2"
sentinelhub = ">=3.11.3,<4"
folium = ">=0.20.0,<0.21"
openai = ">=2.6.0,<3"
opencv = ">=4.10.0,<5"
rich = ">=14.2.0,<15"
geopandas = ">=1.1.1,<2"
requests = ">=2.32.5,<3"
keyboard = ">=0.13.5,<0.14"
shapely = ">=2.0.4,<3"
